export enum TableTypeEnum
{
    INPUT_TABLE_TYPE = 'INPUT_TABLE_TYPE',
    OUTPUT_CALC_TABLE_TYPE = 'OUTPUT_CALC_TABLE_TYPE',
    OUTPUT_RANG_TABLE_TYPE = 'OUTPUT_RANG_TABLE_TYPE',
    OUTPUT_EXT_CALC_TABLE_TYPE = 'OUTPUT_EXT_CALC_TABLE_TYPE'
}